<a href="https://colab.research.google.com/github/fahadrajput99/Natural_language_processing-NLP-/blob/main/word%20to%20vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df=pd.read_csv('/content/Fake.csv')
df2=pd.read_csv('/content/True.csv')

In [2]:
df.drop(columns=["title" , "date" , "subject"], inplace=True)

In [3]:
df2.drop(columns=["title" , "date" , "subject"], inplace=True)

In [4]:
df2['labels']=1

In [5]:
df['labels'] = 0

In [6]:
df = pd.concat([df, df2])

In [7]:
df.shape

(44898, 2)

In [8]:
df.labels.value_counts()

labels
0    23481
1    21417
Name: count, dtype: int64

In [11]:
!python -m spacy download en_core_web_lg

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.7/587.7 MB 2.2 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [12]:
import spacy
nlp=spacy.load("en_core_web_lg")

In [13]:
df['Vector']=df['text'].apply(lambda text: nlp(text).vector)

In [14]:
df

text  labels  \
0      Donald Trump just couldn t wish all Americans ...       0   
1      House Intelligence Committee Chairman Devin Nu...       0   
2      On Friday, it was revealed that former Milwauk...       0   
3      On Christmas day, Donald Trump announced that ...       0   
4      Pope Francis used his annual Christmas Day mes...       0   
...                                                  ...     ...   
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...       1   
21413  LONDON (Reuters) - LexisNexis, a provider of l...       1   
21414  MINSK (Reuters) - In the shadow of disused Sov...       1   
21415  MOSCOW (Reuters) - Vatican Secretary of State ...       1   
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...       1   

                                                  Vector  
0      [-1.6387042, -0.027837504, -1.6619873, -0.2017...  
1      [-1.9558355, 0.5587237, -2.036446, 0.40390933,...  
2      [-1.9058484, -0.04223674, -1.7389339, -0.02855...  
3      [-1.6265213, 0.14619705, -0.5877981, 0.0992525...  
4      [-2.1327376, 1.1017615, -2.4795847, -0.0065187...  
...                                                  ...  
21412  [-1.769936, 0.9660688, -2.1548896, 0.9791884, ...  
21413  [-1.9705169, -0.4991027, -0.6857045, 0.4332028...  
21414  [-1.9645786, 0.3988588, -1.4762843, 0.781844, ...  
21415  [-2.3227742, 0.7447042, -1.2518635, 0.19396096...  
21416  [-2.314285, -0.00053702865, -2.1566231, 1.0006...  

[44898 rows x 3 columns]

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Vector.values, df.labels.values, test_size=0.2, random_state=2022)

In [17]:
import numpy as np
X_train_2d = np.stack(X_train)
x_train_2d = np.stack(X_train)

x_test_2d = np.stack(X_test)

X_train_2d

array([[-1.7532922 ,  1.0043389 , -2.634101  , ..., -1.1346229 ,
        -2.8155665 ,  1.0411011 ],
       [-2.1117015 ,  0.47832075, -1.6635772 , ..., -1.4822944 ,
        -2.1240811 ,  1.0178057 ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-2.3322341 ,  0.09530165, -1.7772561 , ..., -1.8956466 ,
        -1.7054703 ,  1.0234716 ],
       [-1.0528119 ,  0.8606165 , -2.1912756 , ..., -0.40822423,
        -2.812407  ,  0.7938772 ],
       [-1.8167511 ,  0.45220086, -1.799188  , ..., -1.0007334 ,
        -2.8442135 ,  0.5784804 ]], dtype=float32)

In [18]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report
scaler = MinMaxScaler()
X_train_2d = scaler.fit_transform(X_train_2d)
x_test_2d = scaler.transform(x_test_2d)

clf = MultinomialNB()
clf.fit(X_train_2d, y_train)
y_pred = clf.predict(x_test_2d)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.85      0.87      4628
           1       0.85      0.89      0.87      4352

    accuracy                           0.87      8980
   macro avg       0.87      0.87      0.87      8980
weighted avg       0.87      0.87      0.87      8980



In [21]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train_2d, y_train)
y_pred = clf.predict(x_test_2d)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      4628
           1       0.98      0.98      0.98      4352

    accuracy                           0.98      8980
   macro avg       0.98      0.98      0.98      8980
weighted avg       0.98      0.98      0.98      8980



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [20]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(X_train_2d, y_train)
y_pred = clf.predict(x_test_2d)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      4628
           1       0.98      0.98      0.98      4352

    accuracy                           0.98      8980
   macro avg       0.98      0.98      0.98      8980
weighted avg       0.98      0.98      0.98      8980



In [25]:
y_test[:8]

array([0, 0, 1, 1, 0, 1, 1, 1])

In [24]:
model.predict(x_test_2d[:8])

array([0, 0, 1, 1, 0, 1, 1, 1])

In [28]:
!pip install joblib

import joblib
from sklearn.linear_model import LogisticRegression

# ... your existing code to train the 'model' ...

# Save the model
joblib.dump(model, 'model.joblib')

# Later, to load the model:
# loaded_model = joblib.load('model.joblib')

['model.joblib']